spring:
  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    level:
      root: INFO
      com.serviceinfotech.Service: DEBUG
      org.springframework.web: ERROR
logging.level.com.serviceinfotech: DEBUG